### ISSUE TITLE
Ignore certain trait types

### ISSUE THREAD

**Issue by 36changes** [fukuball/rarity-analyser#1]
Hi, loving your work! Could there possibly be a way to ignore certain trait types in the rarity calculations? I have a collection where certain trait types are unique to every NFT - so don't really form part of the rarity of each piece. Thanks.

**Comment by fukuball** [comment]
Don't know how to calculate what you described above, can you give me some example? if we can derive the calculation algorithm, then I can implement it as an other score.

**Comment by 36changes** [comment]
Essentially it would be being able to set in the config file an array of json key/value pairs that are not used when calculating the rarity score and attribute count.

For example in the config.js file a line such as:
ignore_traits: ["B","C","D"],

Using example collection.json below:
{"id": 1,
"name": "A cool NFT #1",
"image": "https://ipfs.io/ipfs/QmZPh1HHUS2etc3WaUqgGmxgAjt5gCJSD1iDcJvYws2V1/nft-image.jpg", 
"description": "Some funny description here.",
"attributes": [
{"trait_type": "A", "value":"0"}, 
{"trait_type": "B", "value":"1"}, // ignored
{"trait_type": "C", "value":"2"}, // ignored
{"trait_type": "D", "value":"3"}, // ignored
{"trait_type": "E","value":"4"},
{"trait_type": "F","value":"5"},
{"trait_type": "G","value":"6"}
],
"external_url": "https://example.com/1"}

Would exclude trait_types "B", "C" and "D" from the rarity score and attribute count calculations.

**Comment by fukuball** [comment]
I see, will implement, thanks!

**Comment by 36changes** [comment]
Awesome thanks! I think would be a useful addition to this for a lot of projects.

**Comment by fukuball** [comment]
Merged https://github.com/fukuball/rarity-analyser/pull/3
