### ISSUE TITLE
Maybe you want to link our rarity tool in the README

### ISSUE THREAD

**Issue by 4nt1m4tt3r** [fukuball/rarity-analyser#7]
I based our rarity tool on your repository and I thought it would be a nice showcase
https://rarity.anticryptopunks.com/

I didn't find an email address to contact you directly, thus I opened this issue here to get a conversation going

**Comment by fukuball** [comment]
Hey, great work, you can edit the readme, and send a pull request, I will merge it.

**Comment by 4nt1m4tt3r** [comment]
Thanks!
Done: https://github.com/fukuball/rarity-analyser/pull/8

**Comment by fukuball** [comment]
Thanks!
